### PR TITLE
Remove "release aggregates going away" notice from index

### PR DESCRIPTION
**Pull request by chutten**
It's not 100% clear that it's only relevant to dist and evo.

### CODE REVIEW

**Review by fbertsch — CHANGES_REQUESTED** [review]
This commit should just be a revert of the previous one. We can reapply the previous one if we want to reuse any of its changes.

**Comment by chutten** [comment]
@fbertsch A partial revert, you mean? Why would that be better than just commenting it out?

**Review by georgf — COMMENTED** [review]
This part makes sense to me. The message will still be shown in the measurements & evolution dashboard.

Could we make it a little more focused on the impact though in the other places?

Maybe something like:
"The data from release users will go away soon, affecting this dashboard and the aggregates service. For context, please read ..."

**Review by fbertsch — APPROVED** [review]
Ah, I see now that it is still showing on the other views. LGTM :)

**Comment by chutten** [comment]
I'll take the rewording request to a different PR

**Pull request merged**
