### PR TITLE
empty() and rebuild the percentiles only if the histogramsList is not empty

### PR DESCRIPTION
**Pull request by o0Ignition0o**
Folloup on #378 :)

### CODE REVIEW

**Comment by chutten** [comment]
What happens with your changes when you go to `http://<your telemetry-dashboard-base>/new-pipeline/dist.html#!max_channel_version=beta%252F58&min_channel_version=beta%252F58&measure=A11Y_TREE_UPDATE_TIMING_MS&product=Firefox`

**Comment by o0Ignition0o** [comment]
screenshot from 2018-01-22 23-38-07
Ok this looks better, but I still need to clean up my mess before I update the PR ^^' 

By the way I'm now able to change the text if the option is not available. @chutten would you like me to prepend or append something such as < ! > or invalid before the labels ? (btw I could do this on any multiselect)

**Comment by chutten** [comment]
Nope! Leaving it be is grand. With the main display starkly blank, showing only the "Possible reasons" explainatory message, the message is clear. Let me know when you'd like my r?

**Comment by o0Ignition0o** [comment]
Ok fine ! Unfortunately I won't be on the computer tonight (CET) so I'll
submit tomorrow if you don't mind :)

**Comment by o0Ignition0o** [comment]
I'm trying to figure out how to publish my fork as a github page, otherwise this should be reviewable ^^

Edit : There you go https://o0ignition0o.github.io/telemetry-dashboard/new-pipeline/dist.html#!max_channel_version=beta%252F58&min_channel_version=beta%252F58&measure=A11Y_TREE_UPDATE_TIMING_MS&product=Firefox :)

**Comment by chutten** [comment]
Looks good to me! It even seems to work if gInitialPageState has no measure in it, from my testing.

**Pull request merged**
