### PR TITLE
Adds label for Mac OS X 10.11 El Capitan

### PR DESCRIPTION
**Pull request by claudiopro**
As the label says

### CODE REVIEW

**Comment by vdjeric** [comment]
Did you test it? It's a static site so you can host it anywhere, e.g. on divshot.io
Also, can you separate the whitespace cleanup into a separate commit

**Comment by claudiopro** [comment]
Hi @vdjeric yes I tested it locally with a python SimpleHttpServer from local dir as recommended. I noticed the whitespace changes only after committing, I use Atom with default settings which trims trailing whitespace. I'll remove it by squashing commits, apologies :sweat:

**Comment by claudiopro** [comment]
@vdjeric please review again, thanks!

**Comment by vdjeric** [comment]
Looks good, you can submit the whitespace fixes as a separate pull request btw. The whitespace kinda bothers me now that I know it's there :)

**Comment by claudiopro** [comment]
@vdjeric lol, ok

**Pull request merged**
