### PR TITLE
Improved Description Display; Fixes #358

### LINKED ISSUE #358: Don't linkify full probe descriptions
On the distribution & evolution dashboard, we now make the whole description a link.
This impedes readability.
Can we instead just add a "learn more" link after the descriptions?

### PR DESCRIPTION
**Pull request by shikhar-scs**
This is a duplicate of #368. I have closed #368 because of some rebasing errors and merge conflicts. Please review here. 

For any other details visit #368 
@georgf

### CODE REVIEW

**Review by georgf — COMMENTED** [review]
This looks clean now, cheers.
We found on the other PR that Icon_External_Link.png is unused, can you remove it?

**Comment by shikhar-scs** [comment]
Yep sure :smile: just recheck in a couple of minutes please!

**Comment by shikhar-scs** [comment]
@georgf 
Just realised that it already has been removed. Please recheck

**Comment by georgf** [comment]
Ah, it actually is loaded from an external source, my bad.

**Review by georgf — APPROVED** [review]
This looks good to me!

**Comment by shikhar-scs** [comment]
Thanx @georgf for merging :smile:

**Comment by georgf** [comment]
Thanks for your contribution.

**Pull request merged**
