### PR TITLE
Add a button to collapse search and filter.

### PR DESCRIPTION
**Pull request by Insiyaa**

### CODE REVIEW

**Comment by Insiyaa** [comment]
https://insiyaa.github.io/telemetry-dashboard/probe-dictionary/

**Comment by Insiyaa** [comment]
Please review:)

**Comment by Insiyaa** [comment]
Hey @georgf , can you please review this PR so that I can make changes for issue #505...:)

**Comment by Sylvia23** [comment]
@Insiyaa , You can anytime work on `other` issues as well. Just `checkout` on a different `branch` and makes changes on that branch for the `issue` you are working on. Then, `push` that branch to the `origin` to make a `pull request` for that issue. This way you don't have to wait for your other issues to be reviewed or get merged. I hope that helps. Thanks!

**Comment by Insiyaa** [comment]
Thanks @Sylvia23 ! Will do this! :)

**Review by georgf — COMMENTED** [review]
Thanks for the proposal Insiyaa!
I'm not sure what problem this solves though, could you clarify this?

**Comment by Insiyaa** [comment]
For better user experience. On small screens, the search and filter takes considerable space hence collapsing gives extra space for probes...

**Comment by georgf** [comment]
But you can scroll down to the probes, right?
I expect users to mostly actively use the search to explore the data, so i'm not sure if adding this functionality helps much.

**Comment by Insiyaa** [comment]
Yeah! Will close this PR...

**Comment by georgf** [comment]
Ok, cheers for the proposal though! :)

**Pull request closed without merging**
