### PR TITLE
Enumerated evolutions

### PR DESCRIPTION
**Pull request by Uberi**
Support enumerated histograms by adding options to show the evolution of individual values of histograms over time.

For example, selecting "0 bucket percentage" means that the shown evolution is the percentage of metrics that are in the 0's bucket for each daily histogram.

See [bug 1188879](https://bugzilla.mozilla.org/show_bug.cgi?id=1188879) for details.

Now live at http://production.telemetry-dashboard.divshot.io/new-pipeline/evo.html.

### CODE REVIEW

**Comment by vdjeric** [comment]
This looks wrong: http://bit.ly/1Mu4hUU 
LOOP_ICE_FINAL_CONNECTION_STATE is an enum with 7 buckets, why am I seeing options like "1262 bucket percentage" and "median"

**Comment by vdjeric** [comment]
TypeError: lines is undefined

STR:

1. Load this 
http://production.telemetry-dashboard.divshot.io/new-pipeline/evo.html#!aggregates=median&cumulative=0&end_date=null&keys=&max_channel_version=nightly%252F43&measure=GC_MS&min_channel_version=nightly%252F40&product=Firefox&sanitize=1&sort_keys=submissions&start_date=null&trim=1&use_submission_date=0
2. Switch to LOOP_ICE_FINAL_CONNECTION_STATE

**Comment by vdjeric** [comment]
Is divshot up to date?

**Comment by Uberi** [comment]
Yep, just uploaded.

**Pull request merged**
