### PR TITLE
Fix #255 : Don't load data until done picking options

### LINKED ISSUE #255: Don't load data until done picking options
The evolutions/histograms UI is too aggressive in updating things before I'm done picking the things I want

### PR DESCRIPTION
**Pull request by Sylvia23**
@chutten , I have tried to implement the solution taking the reference of #381 . 
What other additional changes are required ? Please suggest.
I read the discussion on PR #381, I think the intended solution is that the data gets loaded when we are done with selecting options from all the drop-down menus. 
But the data gets loaded after `3 sec` according to the options that are present at that moment (i.e. after 3 sec) irrespective of they are chosen by the user or they are default values.   
Did I get the discussion right ? Please correct me if I am wrong.

### CODE REVIEW

**Comment by chutten** [comment]
Could you provide a link to the live instance so I can try it out? A feature like this can look sensible in the code but exhibit strange corner cases when a user fiddles with it.

**Comment by Sylvia23** [comment]
@chutten , Yeah, I will make it live after #500 . Thanks!

**Comment by Sylvia23** [comment]
@chutten , I have made it live at [https://sylvia23.github.io/telemetry-dashboard/new-pipeline/dist.html](url).
Please have a look ! Thanks !

**Comment by chutten** [comment]
I don't think the live version is running the code from this branch. When I go to https://sylvia23.github.io/telemetry-dashboard/new-pipeline/src/dist.js it shows the older version of the code.

**Comment by Sylvia23** [comment]
@chutten , I think I had not updated it then. But now it's good to see live. Please check at [https://sylvia23.github.io/telemetry-dashboard/new-pipeline/dist.html](url) and the [changed file](https://sylvia23.github.io/telemetry-dashboard/new-pipeline/src/dist.js).
Thanks!

**Comment by chutten** [comment]
Now that he's back, I'm going to hand this over to @georgf for review

**Comment by Sylvia23** [comment]
Okay . Thanks @chutten ! @georgf Please review. Thanks!

PS : It's not live as of now. I will make it live after #502 .

**Comment by Sylvia23** [comment]
@georgf , It's live now. [Here](https://sylvia23.github.io/telemetry-dashboard/new-pipeline/dist.html) is the link. Please review and suggest changes and additions. Thanks!

**Comment by Sylvia23** [comment]
@georgf Please review whenever you are free.  [Here](https://sylvia23.github.io/telemetry-dashboard/new-pipeline/dist.html) is the live link. Thanks!

**Comment by georgf** [comment]
Sorry that this slipped through.

@chutten Is there something specific i should look at? Or can you handle the review?

**Comment by chutten** [comment]
The live link appears to not have any delay in it. Selecting items loads the new selection immediately. Is it still live?

**Comment by chutten** [comment]
Closing due to inactivity. We can reopen this if it becomes active again in future.

**Pull request closed without merging**
