### PR TITLE
Fix #447: Use checkboxes in dashboards "advanced settings"

### LINKED ISSUE #447: Use checkboxes in dashboards "advanced settings"
The "advanced settings" in the distribution and evolution dashboard should just be checkboxes instead of radio buttons.

This will require a bit of rewording and reordering of elements so that it makes sense.

### PR DESCRIPTION
**Pull request by paucaro**
@chutten I created my local branch with my changes to merge. :)

### CODE REVIEW

**Comment by paucaro** [comment]
Maybe I could close this pull #465

**Review by chutten — COMMENTED** [review]
Looks good. Now we just need one change: It needs a descriptive commit message : )

Here's an article about what makes a good commit message: https://chris.beams.io/posts/git-commit/

We won't be nearly that strict, but it has some good points about a short summary, longer explanations (if necessary) and putting the Fixes parts towards the bottom.

Work that in and we'll get this merged.

**Comment by paucaro** [comment]
I have changed the commit following the tips of the article (I feel that every day I learn a lot :) ) Thanks for your help @chutten @georgf

**Comment by georgf** [comment]
Hi @PaulaAsto. Sorry, it seems like this PR fell between the cracks.
Is this ready for review?
Could you provide a [live link](https://github.com/mozilla/telemetry-dashboard/#submitting-pull-requests-for-the-dashboard) for the changes?
Thanks!

**Comment by paucaro** [comment]
Hi @georgf . Of course, the live link is this: https://paulaasto.github.io/telemetry-dashboard/

**Review by georgf — COMMENTED** [review]
Thanks, this seems to work well from testing it!

One thing that stands out is that the advanced settings box always seems to open up. However, comparing to the current telemetry.mozilla.org state, this is probably not a new issue.

The code looks sensible to me, but i have to leave a detailed review to @chutten who knows this code better.

**Review by chutten — APPROVED** [review]
Looks good to me, thank you for your patience, I'm sorry I missed this one.

**Pull request merged**
