### PR TITLE
Bug 1509416 - Add new error codes, coalesce small pie slices in version distribution pie chart, fix a couple of minor bugs, and make some of the wording clearer.

### PR DESCRIPTION
**Pull request by RobertTStrong**
Bug 1509416 - Add new error codes, coalesce small pie slices in version distribution pie chart, fix a couple of minor bugs, and make some of the wording clearer.

### CODE REVIEW

**Comment by RobertTStrong** [comment]
There is a working copy available here
http://exchangecode.com/robert/work/dashboard/

**Review by chutten — APPROVED** [review]
LGTM

**Comment by chutten** [comment]
Do you want anyone else to take a look before it's merged?

**Comment by RobertTStrong** [comment]
No one else needs to look at it before merging. Thanks!

**Pull request merged**
