### PR TITLE
Changed fonts to improve readability and look.

### PR DESCRIPTION
**Pull request by raghav-kukreti**
The 67 changed files are probably because of different line endings but everything else is the same.
I simply changed fonts and different readability options for a better look.

### CODE REVIEW

**Review by chutten — CHANGES_REQUESTED** [review]
I'm afraid we will not be able to evaluate your changes with all the noise caused by the line endings being different :S

Please fix the line endings issue (maybe your local git config has a `crlf` setting?) and resubmit.

**Comment by georgf** [comment]
Raghav, could you show a screenshot of the changes you made?
Or a live-link of the changed dashboard?
Thanks!

**Comment by raghav-kukreti** [comment]
Of course. Will get the line endings checked.
https://raghav-kukreti.github.io/telemetry-dashboard

**Comment by georgf** [comment]
Thanks. Looking at this, i'm not sure if the font changes improve readability.
What is the specific improvement you are aiming for?

**Comment by chutten** [comment]
Closing due to inactivity. Please let me know if you have any questions about future contributions.

**Pull request closed without merging**
