### PR TITLE
Fixed #437: Add icons for some actions in the telemetry dashboard 

### LINKED ISSUE #437: Add icons for some actions in the telemetry dashboard
Some actions in dist.html & evo.html could use icons to be easier to notice.
The buttons at the top-right and the "advanced settings" come to my mind.

We include font-awesome 4, so we can use [icons from there](https://fontawesome.com/v4.7.0/icons/).

### PR DESCRIPTION
**Pull request by paucaro**
I added the font-awesome icons in some actions in dist.html & evo.html, I attachment pictures about it. Any suggestion is welcome. Also, I was thinking about putting icons and fixing the structure in tutorial.html
image
image

### CODE REVIEW

**Comment by georgf** [comment]
That's coming along nicely!

I think for the tutorial, a help / question mark icon would probably work better.
For the advanced settings, could we use an icon with a single cogwheel? The multiple ones look a bit busy.

One ask: could you give us a live link to your changes? [See here](https://github.com/mozilla/telemetry-dashboard#submitting-pull-requests-for-the-dashboard) for the details.

**Comment by paucaro** [comment]
Yes, of course. I've done my changes and this is the live link:  https://paulaasto.github.io/telemetry-dashboard/

**Review by georgf — APPROVED** [review]
This looks good to me, thanks!

**Comment by georgf** [comment]
Thanks for the contribution Paula!
Would you like to follow up on this by working on #447?

**Pull request merged**
