### PR TITLE
Add a Stability Dashboard

### PR DESCRIPTION
**Pull request by chutten**
We have all of this lovely crash data in crash_aggregates, and arewestableyet.com has set the stage for how relman likes to look at crash data. Let's get some peanut butter in this chocolate.

Live-hosted here: http://chutten.github.io/telemetry-dashboard/stability/

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-dashboard/263)

### CODE REVIEW

**Comment by bsmedberg** [comment]
Please update or replace t.m.o/crashes with this. Also if this is specific to crashes, I recommend that you use the crashes/ URL. If OTOH in the future we want to expand this to include other non-crash stability data for release drivers, then stability/ is the better spot.

**Comment by chutten** [comment]
New live-hosted link: http://chutten.github.io/telemetry-dashboard/crashes/

**Comment by fbertsch** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[crashes/index.html, line 106 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-dashboard/263#-KXCAFY4uDx2CxVre_Vi:-KXCAFY4uDx2CxVre_Vj:b-261cg2) ([raw file](https://github.com/mozilla/telemetry-dashboard/blob/1649e709347d0f3a78eb448946c5ff1b03e28ce1/crashes/index.html#L106)):*
> ```HTML
>     }
>     if (row.channel in gMap[row.activity_date]) {
>       if (gMap[row.activity_date][row.channel].usage_khours > row.usage_khours ) {
> ```

So - should we be using the most recent version for this date, instead of maximum usage hours? Could use https://product-details.mozilla.org/1.0/firefox.json to determine what the version should be for a date.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-dashboard/263)*

**Comment by chutten** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[crashes/index.html, line 106 at r2](https://reviewable.io:443/reviews/mozilla/telemetry-dashboard/263#-KXCAFY4uDx2CxVre_Vi:-KXC_cXKDf6q-jMPrpwx:b-tm0sjc) ([raw file](https://github.com/mozilla/telemetry-dashboard/blob/1649e709347d0f3a78eb448946c5ff1b03e28ce1/crashes/index.html#L106)):*
<details><summary><i>Previously, fbertsch (Frank Bertsch) wrote…</i></summary>
> So - should we be using the most recent version for this date, instead of maximum usage hours? Could use https://product-details.mozilla.org/1.0/firefox.json to determine what the version should be for a date.
</details>
Sadly, product-details doesn't provide what the latest version is for dates in the past or future. It can tell us what the current version is, but not when that changed. And what it changed from.

I think for now I'd like to leave it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-dashboard/263)*

**Comment by fbertsch** [comment]
:lgtm:

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-dashboard/263#-:-KXCak19_O3N9KuXa2li:bnfp4nl)*

**Pull request merged**
