### PR TITLE
Issue #474: Link to use counter dashboard for selections that include "USE_COUNTER2"

### PR DESCRIPTION
**Pull request by ecomerford**
Hi @georgf , would you mind taking a look at this when you get the chance?

You can see it live [here](https://ecomerford.github.io/telemetry-dashboard/new-pipeline/dist.html#!cumulative=0&end_date=2018-03-08&keys=__none__!__none__!__none__&max_channel_version=nightly%252F60&measure=USE_COUNTER2_CONSOLE_TABLE_DOCUMENT&min_channel_version=nightly%252F57&processType=*&product=Firefox&sanitize=1&sort_keys=submissions&start_date=2018-01-22&table=0&trim=1&use_submission_date=0).

The only issue I'm having now is that if there is no data for the selection, the code doesn't create a new link, and if you switch to a non-use counter measure that doesn't have enough data to load a histogram, then the link does not get hidden. 

I'm not sure why this is happening- when I console log the `group` variable it seems to be updating each time regardless of the data. But when I console log the `useCounterLink` variable, that does not appear to be updating if there is too little data.

Do you have any thoughts on this?

Thank you!

### CODE REVIEW

**Comment by georgf** [comment]
Cheers, that's good functional progress!

I think what happens here is that we hit [this branching](https://github.com/mozilla/telemetry-dashboard/blob/aabe22aee2c7096f1dd3bc83d30be92ecea8ca78/new-pipeline/src/dist.js#L872), so to clear/hide the link you'd have to handle it in this function (similar for evo.js).

With the current HTML structure i think the element fits better next to the `dist-caption-link` element.
How about moving it there and using a `getUsecounterLink()` function for the contents?
That would follow the current pattern.

**Comment by ecomerford** [comment]
Sorry for the delay! I've gone ahead and moved the link to be right below the `dist-caption-link` element.

When you say handle it in "this" function, are you referring to the new function I'm creating or the branching functions in evo.js and dist.js?

**Comment by georgf** [comment]
No worries!

> When you say handle it in "this" function, are you referring to the new function I'm creating or the branching functions in evo.js and dist.js?

Ah, i mean the branching functions. I was thinking we can add this similar to how `getDescriptionLink()` works.

**Comment by georgf** [comment]
I'll close this PR temporarily so it doesn't show up in our tracked work.
We can reopen it any time, just let me know! :)

**Pull request closed without merging**
