### PR TITLE
More cleanup!

### PR DESCRIPTION
**Pull request by vitillo**
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-dashboard/275)

### CODE REVIEW

**Comment by chutten** [comment]
Wow, removing telemetry.js v1. End of an era.

**Comment by chutten** [comment]
Are there any steps we need to take with disqus to deregister, delete accounts, remove configurations or stuff?

**Comment by chutten** [comment]
Erg. travis-ci is trying to run v1 telemetry.js tests. (we have tests?!) That'll need to be fixed.

**Comment by vitillo** [comment]
Good question; I don't know who owns the disqus account. @mreid-moz ?

**Comment by vitillo** [comment]
I removed the tests.

**Comment by vitillo** [comment]
I disabled travis and removed the tests.

**Comment by mreid-moz** [comment]
Looks like it's owned by `perf@mozilla.com`. Vladan set it up a couple of years ago, I don't think I have admin for it. @georgf do you have details?

**Comment by georgf** [comment]
> Looks like it's owned by perf@mozilla.com. Vladan set it up a couple of years ago, I don't think I have admin for it. @georgf do you have details?

No idea, sorry.

**Comment by georgf** [comment]
> Are there any steps we need to take with disqus to deregister, delete accounts, remove configurations or stuff?

As mentioned on IRC, disqus is used and there is actual information in a few individual probe comments.
Before we do any of that, lets at least triage and make sure the probe description are updated to match that existing information.

**Comment by georgf** [comment]
The context is in [the disqus fhr-dev thread](https://mail.mozilla.org/pipermail/fhr-dev/2016-September/thread.html).

**Comment by vitillo** [comment]
@georgf Do you have a list of all the comments by chance?

**Comment by vitillo** [comment]
@vdjeric can you please send us the access credentials of the Disqus account?

**Comment by chutten** [comment]
On @georgf's behalf, here are the comments:

 http://disq.us/p/10ldbqx
* http://disq.us/p/10lem9p
* http://disq.us/p/10l4qsj
* http://disq.us/p/10gxa1y

Most of them are mapping the numbers to the labels, which we do elsewhere in the hgram descriptions. I would r+ patches that added that information to the descriptions in Histograms.json.

**Comment by chutten** [comment]
I have filed [bug 1329227](https://bugzilla.mozilla.org/show_bug.cgi?id=1329227) for the work.

**Comment by vdjeric** [comment]
We did a password reset, Mark will have the password

**Comment by mreid-moz** [comment]
Can confirm, I now have the password for the `telemetrydash` account. Thanks @vdjeric

**Review by chutten — APPROVED** [review]

**Pull request merged**
