### PR TITLE
Fix #448: NavBar is now fixed to the top of the Probe Dictionary page

### LINKED ISSUE #448: Make the probe-dictionary search results header sticky
In the [probe-dictionary search results](https://telemetry.mozilla.org/probe-dictionary/), it would be great if the table header is always in view, no matter where you scroll to.

Chris mentioned that [`position: sticky`](https://developer.mozilla.org/en-US/docs/Web/CSS/position) might help here.

### PR DESCRIPTION
**Pull request by rosexw**
Hi Georg,

This was a great first step to get familiar with this project and something that I could do without too much time. Thank you for assigning it to me.

The NavBar is fixed to the top of the Probe Dictionary Page using Position:fixed, and I adjusted the body portion to the amount as it was originally.

Thanks,

Rose

### CODE REVIEW

**Review by georgf — COMMENTED** [review]
Thanks!
This is fixing the navigation bar though, while we'd like to make the search header bar sticky:
screen shot 2018-03-08 at 12 17 16

Could you setup a live instance? This makes reviewing much easier, [details are here](https://github.com/mozilla/telemetry-dashboard/#submitting-pull-requests-for-the-dashboard).

**Comment by rosexw** [comment]
Hi @georgf,

I tried fixing the search header (the tr for that th row) with position: sticky using localhost:8080 (I am just using web developer inspect tools to check and tried it with the code as well). I thought that this was a good guide on what position: sticky does: https://css-tricks.com/position-sticky-2/. However, that did not work and still scrolls past it. 

I have my own website at rosexw.github.io, I created a project folder for this NavBar, https://rosexw.github.io/probe-dictionary/, but it doesn't seem to have the fixed NavBar change, even after I added it into this repo.

Thanks,

Rose

**Comment by georgf** [comment]
This is addressing #448.

**Comment by georgf** [comment]
> I have my own website at rosexw.github.io, I created a project folder for this NavBar, https://rosexw.github.io/probe-dictionary/, but it doesn't seem to have the fixed NavBar change, even after I added it into this repo.

Interesting. Have you checked in the "Github Pages" settings that it is set to the right branch?
The commits here are on the "probe-dictionary-position-sticky" branch, i think by default GH Pages serves from the "gh-pages" branch or master.

**Comment by georgf** [comment]
I went researching this a little and found some working solutions:
- [This has a solution](https://codepen.io/tjvantoll/pen/JEKIu), but there is a lot of other additional code in this.
- [This looks straight-forward](http://jsfiddle.net/yeAhU/261/) (comes from [here](https://stackoverflow.com/questions/37264905/fixed-table-header-with-scrolling-page-body)).

Do these approaches work?

**Comment by chutten** [comment]
Oh, those are table parts? There are some known issues with `position: sticky` and some table elements: https://caniuse.com/#feat=css-sticky

Specifically, Firefox only supports `position: sticky` on table parts as of version 59.

**Comment by georgf** [comment]
Aha!
Then let's try the second approach i linked.

**Comment by rosexw** [comment]
Good morning,

Thanks for all the advice, @georgf and @chutten!

I have found people talking about this issue [here](https://bugzilla.mozilla.org/show_bug.cgi?id=975644) and [here](https://github.com/dollarshaveclub/stickybits/issues/143) as well. I have version 58.0.2 installed, and when I go to the About Firefox tab, it tells me that it's the most updated version. However, there are versions 59-62 listed on CanIUse.

When I use the 
`display: table` 
and 
`display: block; 
position: sticky; 
position: -webkit-sticky; 
top: 0;`
It gives this effect of nonuniform columns and overlap. I guess I can use CSS to fix this.

Or if there's another way, like using JavaScript/jQuery to fix it until it scrolls down to a certain height, would that be better? 

screen shot 2018-03-10 at 9 24 50 am

**Comment by rosexw** [comment]
In the meantime, I can see if I can download Firefox version 59-62.

**Comment by georgf** [comment]
We will need to support versions before Firefox 59, so i don't think we can use `position: sticky` currently.

**Comment by rosexw** [comment]
OK, great! I was just about to ask that.

**Comment by rosexw** [comment]
Hi @georgf,

I have spent a few hours yesterday and a few hours this morning working on this, trying to get a solution.
I have tried position: sticky with display:table (it breaks the structure of the whole table when this is applied), but found out that jQuery works better. However, the columns aren't aligned properly and it doesn't return to the original spots after we scroll back up. I have moved it down to below the navbar with padding...maybe we should create global variables for it (Sass has this) so we can easily change the height of the navbar.

I do have Bridge School (bridgeschool.io) homework to complete this weekend and we will start our final projects next week. I may not have as much time once that starts (that's what my TA there had told me, as she was part of the last cohort). We have been learning JavaScript(ES6), React, and Redux there. My cohort (cohort 3) in the Bridge School program ends April 12th.

Thank you to you and @chutten for helping me with these contributions and thank you for all the advice, as I'm still a junior developer (only started web development last year). Have a good vacation, Georg!

screen shot 2018-03-10 at 11 27 45 am

**Comment by rosexw** [comment]
currently deployed here: https://rosexw.github.io/probe-dictionary/

**Comment by georgf** [comment]
Cheers for lining out the details here.
Given your time, this sounds like we should just pause this or have someone else pick it up if they are interested :)

Sorry, this became more involved than i expected, i thought it had a more clear solution!

**Comment by rosexw** [comment]
Thank you, Georg!
No worries, I had thought the same when I first tried it. Thanks for all your help and support in this project!

**Comment by chutten** [comment]
Closing this for now

**Comment by rosexw** [comment]
Thanks, Chris!

**Pull request closed without merging**
