### PR TITLE
Add link to dataset status page

### PR DESCRIPTION
**Pull request by jklukas**
See these changes rendered at https://jklukas.github.io/telemetry-dashboard/

### CODE REVIEW

**Comment by chutten** [comment]
Is bikeshedding appropriate here? I love having this link on the front page, but maybe in "Other tools"?

**Comment by jklukas** [comment]
> Is bikeshedding appropriate here? I love having this link on the front page, but maybe in "Other tools"?

That's totally fair. Will move.

**Comment by jklukas** [comment]
Pushed a new commit to move the link. Demo live at https://jklukas.github.io/telemetry-dashboard/

**Review by chutten — APPROVED** [review]
I like it.

Would you like me to to wait for Georg's input before I merge this?

**Comment by jklukas** [comment]
Went ahead and merged since I had the access.

**Pull request merged**
