### PR TITLE
Fix 444 : Error showing detail view for use-counters in probe-dictionary

### PR DESCRIPTION
**Pull request by mindip**
Fix for the issue linked below.
https://github.com/mozilla/telemetry-dashboard/issues/444

### CODE REVIEW

**Comment by chutten** [comment]
Can you put this up as a live instance so we can test it out before review? gh-pages are a common way to do this and can be enabled in your fork's settings. More details are available in the README

**Comment by mindip** [comment]
Sure, here's a link to [the view](https://mindip.github.io/telemetry-dashboard/probe-dictionary/?detailView=histogram%2FUSE_COUNTER2_DATATRANSFER_ADDELEMENT_PAGE) mentioned in the issue.

**Review by chutten — APPROVED** [review]
Looks good to me!

**Comment by chutten** [comment]
Thank you for your contribution!

**Pull request merged**
