### PR TITLE
bug 1324526 - Remove links to dead dashboards

### PR DESCRIPTION
**Pull request by chutten**
This should be the bulk of it. Fennec App Not Responding may also need delisting. Awaiting s.kaspari's ni? on the bug.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-dashboard/271)

### CODE REVIEW

**Comment by mreid-moz** [comment]
Cool, does this mean I can kill the slowsql job too?

**Comment by chutten** [comment]
@mreid-moz Sure! So long as it's just as easy to restart as it is to revert these changes in the event that someone requires the data.

**Comment by mreid-moz** [comment]
Yep, pretty easy.

**Comment by vitillo** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1, 11 of 11 files at r2, 1 of 1 files at r3, 7 of 7 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 13 of 13 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-dashboard/271#-:-Ka1IAO38QLu8EsTmu3Q:bnfp4nl)*

**Pull request merged**
