### PR TITLE
fixes chart lables

### PR DESCRIPTION
**Pull request by shiri1248**
#575  fixes

### CODE REVIEW

**Review by chutten — CHANGES_REQUESTED** [review]
This code may or may not make a difference as it controls what versions are useful to put in the channel+version dropdowns.

This suggests that the "aurora" labels on the graphs must be coming in from the data. This means intercepting the data just before `MG.data_graphic` is called and mapping "aurora" to "dev edition"

Do you understand what I mean?

**Comment by shiri1248** [comment]
@chutten  thanks for reviewing. I'll take care of it :)

**Comment by chutten** [comment]
@shiri1248 Do you need any help?

**Comment by shiri1248** [comment]
yes @chutten   it would be helpful :)

**Comment by chutten** [comment]
I think the problem lies in the data returned from the aggregator itself by the `Telemetry.getEvolution` call in `evo.js`. It probably has the channel set to "aurora". Luckily, we convert it to `Line` objects before we graph them, so maybe in the `Line` constructor we can take `channelVersion` and replace `aurora` with `dev edition` in it?

Do you think you'd like to give that a try, @shiri1248 ?

**Comment by shiri1248** [comment]
yes @chutten  I will give a try.

**Comment by chutten** [comment]
This PR appears to be abandoned. Closing.

**Pull request closed without merging**
