### PR TITLE
Make selectors scroll the last selected items into view.

### PR DESCRIPTION
**Pull request by Uberi**
Ref: #176.

Now live at http://planner-frog-12114.bitballoon.com/.

### CODE REVIEW

**Comment by vdjeric** [comment]
There's a bug. STR:

1. Enter "pause" in the histogram name box
2. Select GC_MAX_PAUSE_MS histogram
3. Open histogram name box

Expected: list should be scrolled to GC_MAX_PAUSE_MS
Actual: the beginning of the list is in view

**Comment by Uberi** [comment]
New version is now up at http://money-lender-mona-33020.bitballoon.com/.

**Comment by vdjeric** [comment]
Can you do anything about the "blink"?

STR:
1. Type "uptime" in the histogram box. Observe how the list shrinks down to only one matching histogram
2. Select SIMPLE_MEASURES_UPTIME histogram
3. Open histogram name box again

Expected: histogram name box opens, cued to the currently selected histogram's name in the full list

Actual: histogram name box opens to its previous view first (only 1 histogram), then almost immediately resets to the correct view (full list cued to SIMPLE_MEASURES_UPTIME)

**Comment by Uberi** [comment]
The blink is caused by the way the selector library works, so it would require library patching. Could be done, but would be pretty messy.

**Comment by vdjeric** [comment]
Well I guess this blink isn't new behaviour, and the new functionality **is** better. Merged.

**Comment by vdjeric** [comment]
Deployed too

**Pull request merged**
