### PR TITLE
FIX #469: Rename Dashboard Home to Telemetry Portal

### LINKED ISSUE #469: Rename "Dashboards Home" to "Telemetry portal"
In `new-pipeline/dist.html` and `evo.html`, we should rename the "Dashboards Home" button to "Telemetry portal".

### PR DESCRIPTION
**Pull request by gargshruti30**

### CODE REVIEW

**Comment by gargshruti30** [comment]
@georgf can you please merge this PR

**Comment by badboy** [comment]
Hi @gargshruti30. georgf is on vacation for the next little while, but chutten will be responsible in the meantime.

However, you committed your IDE's project files. Please remove them from the commit in order to get it merged.
You might want to set up a [global gitignore file](https://help.github.com/articles/ignoring-files/#create-a-global-gitignore) to globally ignore these files in git repositories.

**Comment by gargshruti30** [comment]
@badboy I removed my IDE's project files.

@chutten Can you please now merge it.

**Comment by badboy** [comment]
@gargshruti30 As not everyone is using the same IDE as you, it makes more sense to ignore the files on your local machine using a global gitignore file and not change the project's `.gitignore`.

**Comment by gargshruti30** [comment]
@badboy Done.
Can you please merge this PR now.

**Comment by gargshruti30** [comment]
@badboy Can you please tell me more issues to work upon.

**Comment by gargshruti30** [comment]
@badboy Can you please merge this PR now.

**Pull request closed without merging**
