### PR TITLE
bug 1411305 - Notify users that the unrepresentative release data's going away.

### PR DESCRIPTION
**Pull request by chutten**
'cause it is. Soonish.

### CODE REVIEW

**Comment by chutten** [comment]
Live preview: http://chutten.github.io/telemetry-dashboard/

**Review by fbertsch — APPROVED** [review]
🚢

**Comment by georgf** [comment]
This is a bit out of context on the TMO landing page, i can't tell what this actually affects without reading the full blog post.
Can we make clear this only affects aggregates and the distribution/evolution dashboards?
Is it sufficient to show this notice on the distribution/evolution dashboard?

**Comment by chutten** [comment]
I'm fine with removing it from the index.

**Pull request merged**
