### PR TITLE
removed prism files; Solves #354

### PR DESCRIPTION
**Pull request by shikhar-scs**
As suggested by @chutten at #354 , neither of the prism files i.e. `prism.js` and `prism.css` were actually being used in the project. Thus, I have removed them safely.

Please review.

### CODE REVIEW

**Review by chutten — APPROVED** [review]

**Comment by chutten** [comment]
Thank you for your contribution! Do you need help finding something new to work on?

**Comment by shikhar-scs** [comment]
@chutten Welcome. Also I would be thankful if you could help me locate some bugs having difficulty above the beginner level. That would be of much help.

**Comment by chutten** [comment]
@shikhar-scs  #257 and #258 and #259 have a bit more to them. Do any of those strike your fancy?

**Comment by shikhar-scs** [comment]
Yeah Sure, I'll try and take up atleast a couple of them. @chutten

**Pull request merged**
