### PR TITLE
Handle large urls by splitting them in half.

### PR DESCRIPTION
**Pull request by chutten**
Issue #242

Some versions have been long-lived enough for clients to have submitted
data from them over _years_. This results in a long request URL at the aggregator,
which doesn't handle it well.

So assert if we get a long one, and split large submission-date-dominated
urls in half before requesting.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-dashboard/244)

### CODE REVIEW

**Comment by chutten** [comment]
Tested by using https://chutten.github.io/telemetry-dashboard/v2/telemetry.js in place of the legit one on [this](https://telemetry.mozilla.org/dashboard-generator/?channel=beta&version=39&metric=CERT_VALIDATION_SUCCESS_BY_CA&useSubmissionDate=true&sanitize=false&trim=true&compare=&sensibleCompare=true&evoVersions=1&filters=) dashboard-generator-generated dashboard 

It's a rough patch. The larger problem might be system design. The aggregator's API isn't designed to handle these long URIs, but they're valid requests. Maybe we should allow putting the request in the body. Maybe we should allow a date range (to telemetry.js and to the aggregator). 

Thoughts to ponder.

**Comment by fbertsch** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[v2/telemetry.js, line 314 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-dashboard/244#-KPT701fwdFmSAOS-jCR:-KPT701gixB_E93raFgq:b80e5kx) ([raw file](https://github.com/mozilla/telemetry-dashboard/blob/04086eeb42394531ba28a324d6508ae80a012200/v2/telemetry.js#L314)):*
> ```JavaScript
>     assert(typeof url === "string", "`url` must be a string");
>     assert(typeof callback === "function", "`callback` must be a function");
>     assert(url.length <= Telemetry.MAX_URL_LENGTH, "`url` is too long (" + url.length + " > 4094)");
> ```

Probably should use MAX_URL_LENGTH in assert string as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-dashboard/244)*

**Comment by fbertsch** [comment]
:lgtm:

I would vote for the date range submission in the future.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-dashboard/244#-:-KPTUECvJE8skDzkeNwg:b-52py7r)*

**Comment by fbertsch** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[v2/telemetry.js, line 314 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-dashboard/244#-KPT701fwdFmSAOS-jCR:-KPTUaKAZ--IJu8Qqw1F:b32w0x) ([raw file](https://github.com/mozilla/telemetry-dashboard/blob/04086eeb42394531ba28a324d6508ae80a012200/v2/telemetry.js#L314)):*
<details><summary><i>Previously, fbertsch (Frank Bertsch) wrote…</i></summary>
> Probably should use MAX_URL_LENGTH in assert string as well.
</details>
OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-dashboard/244)*

**Comment by chutten** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-dashboard/244)*

**Comment by chutten** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-dashboard/244)*

**Comment by chutten** [comment]
Yeah, I dunno how Reviewable works either. I don't see any unresolved discussions preventing the review from closing... Eh, well.

**Pull request merged**
