### PR TITLE
Bug 1299490 added Submissions to filter

### PR DESCRIPTION
**Pull request by aearl16**
@chutten - Changed line 230, added submissions to the list of strings.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-dashboard/309)

### CODE REVIEW

**Comment by chutten** [comment]
Have you tested it? Does it work?

**Comment by aearl16** [comment]
@chutten - I believe so. We got the 'submissions' in the drop down list when we opened the page.

**Comment by chutten** [comment]
@aearl16 That's a good first step. The more direct test is to, after the page completely loads, select "submissions" from the dropdown so it populates the plot. Then copy the URL into a fresh tab and load it.

The new tab must have the submissions line on the plot to pass the test.

**Comment by aearl16** [comment]
We did do that, but when the page is opened and we clicked submissions the page says the data is no longer available.

**Comment by chutten** [comment]
That's to be expected. If you unselect all of the aggregates, it has nothing to show. Thank you!

**Comment by aearl16** [comment]
Ya no problem.

**Pull request merged**
